[custom]
; ==============================================================================
; 基础设置
; ==============================================================================
add_emoji=true
remove_old_emoji=true

; ==============================================================================
; 策略组设置 (供 Monolithic 模式使用)
; ==============================================================================
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`🇭🇰 香港节点`🇹🇼 台湾节点`🇯🇵 日本节点`🇸🇬 狮城节点`🇺🇸 美国节点`🔯 故障转移`🎯 全球直连
custom_proxy_group=🇭🇰 香港节点`url-test`.*(港|HK|Hong).*`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾节点`url-test`.*(台|TW|Tai).*`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`.*(日本|JP|Japan).*`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`.*(新|SG|Sing).*`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国节点`url-test`.*(美|US|United).*`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择`url-test`.*`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🔯 故障转移`fallback`.*`http://cp.cloudflare.com/generate_204`300
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`🎯 全球直连
custom_proxy_group=📺 流媒体`select`[]🚀 节点选择`🎯 全球直连
custom_proxy_group=🎯 全球直连`select`DIRECT

[rulesets]
; ==============================================================================
; 规则设置 ( Loyalsoldier 规则集 )
; ==============================================================================
ruleset=📺 流媒体,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/netflix.txt
ruleset=📺 流媒体,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/youtube.txt
ruleset=🌍 国外媒体,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegram.txt
ruleset=🌍 国外媒体,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt
ruleset=🌍 国外媒体,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cn.txt
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🚀 节点选择,[]FINAL
