import sys
import os
import re
import time
import socket
import concurrent.futures
import ssl
import yaml

# Register constructor for !<str> tags generated by subconverter
yaml.SafeLoader.add_constructor('str', lambda loader, node: loader.construct_scalar(node))

import maxminddb
import json
import urllib.parse

# Valid ALPN protocol identifiers for Mihomo (TLS Application-Layer Protocol Negotiation)
VALID_ALPN_PROTOCOLS = {'h2', 'h3', 'http/1.1', 'http/1.0', 'h2c'}

COUNTRY_NAMES = {
    "HK": "香港", "TW": "台湾", "JP": "日本", "SG": "新加坡", "US": "美国",
    "KR": "韩国", "GB": "英国", "FR": "法国", "DE": "德国", "RU": "俄罗斯",
    "CA": "加拿大", "AU": "澳大利亚", "IN": "印度", "IR": "伊朗", "TR": "土耳其",
    "NL": "荷兰", "CH": "瑞士", "SE": "瑞典", "NO": "挪威", "DK": "丹麦",
    "FI": "芬兰", "IT": "意大利", "ES": "西班牙", "PT": "葡萄牙", "BE": "比利时",
    "AT": "奥地利", "PL": "波兰", "CZ": "捷克", "SK": "斯洛伐克", "HU": "匈牙利",
    "RO": "罗马尼亚", "BG": "保加利亚", "GR": "希腊", "IE": "爱尔兰", "NZ": "新西兰",
    "ZA": "南非", "EG": "埃及", "AE": "阿联酋", "SA": "沙特", "IL": "以色列",
    "TH": "泰国", "VN": "越南", "MY": "马来西亚", "PH": "菲律宾", "ID": "印度尼西亚",
    "MO": "澳门", "KP": "朝鲜", "MN": "蒙古", "MM": "缅甸", "KH": "柬埔寨",
    "LA": "老挝", "NP": "尼泊尔", "BD": "孟加拉国", "PK": "巴基斯坦", "LK": "斯里兰卡",
    "MX": "墨西哥", "BR": "巴西", "AR": "阿根廷", "CL": "智利", "CO": "哥伦比亚",
    "PE": "秘鲁", "UN": "未知地区",
    "IQ": "伊拉克", "KG": "吉尔吉斯斯坦", "SC": "塞舌尔",
    "UA": "乌克兰", "KZ": "哈萨克斯坦", "UZ": "乌兹别克斯坦",
    "AZ": "阿塞拜疆", "GE": "格鲁吉亚", "AM": "亚美尼亚",
    "RS": "塞尔维亚", "HR": "克罗地亚", "SI": "斯洛文尼亚",
    "LT": "立陶宛", "LV": "拉脱维亚", "EE": "爱沙尼亚",
    "IS": "冰岛", "LU": "卢森堡", "MT": "马耳他",
    "CY": "塞浦路斯", "MA": "摩洛哥", "NG": "尼日利亚",
    "KE": "肯尼亚", "TW": "台湾",
}

MIN_NODES_FOR_GROUP = 5

def iso_code_to_flag(code):
    if len(code) != 2 or not code.isalpha():
        return "🌍"
    return chr(0x1F1E6 + ord(code[0].upper()) - 0x41) + chr(0x1F1E6 + ord(code[1].upper()) - 0x41)

class FilterMetrics:
    def __init__(self, name):
        self.name = name
        self.start_time = 0.0
        self.end_time = 0.0
        self.input_count = 0
        self.output_count = 0
        
    def start(self, count):
        self.start_time = time.perf_counter()
        self.input_count = count
        
    def end(self, count):
        self.end_time = time.perf_counter()
        self.output_count = count
        
    @property
    def duration_ms(self):
        return (self.end_time - self.start_time) * 1000.0
        
    @property
    def filtered_count(self):
        return self.input_count - self.output_count
        
    @property
    def filter_rate_pct(self):
        if self.input_count == 0:
            return 0.0
        return (self.filtered_count / self.input_count) * 100.0

class GeoIPLookup:
    def __init__(self, db_path):
        self.db_path = db_path
        self.reader = None
        
    def __enter__(self):
        if os.path.exists(self.db_path):
            try:
                self.reader = maxminddb.open_database(self.db_path)
            except Exception as e:
                print(f"Error opening GeoIP DB: {e}")
        else:
            print(f"GeoIP Database not found at: {self.db_path}")
        return self
        
    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.reader:
            self.reader.close()
            
    def lookup(self, ip):
        if not self.reader or not ip:
            return 'UN'
        try:
            res = self.reader.get(ip)
            if res:
                code = res.get('country', {}).get('iso_code')
                if code:
                    return code.upper()
        except Exception:
            pass
        return 'UN'

def check_tcp_port(server, port, timeout=1.0):
    try:
        addr_info = socket.getaddrinfo(server, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
        for res in addr_info:
            af, socktype, proto, canonname, sa = res
            s = socket.socket(af, socktype, proto)
            s.settimeout(timeout)
            try:
                s.connect(sa)
                s.close()
                return True, sa[0]
            except Exception:
                continue
        return False, None
    except Exception:
        return False, None

def check_all_proxies_connectivity(proxies, max_workers=100):
    alive_proxies = []
    
    def worker(p):
        server = p.get('server')
        port = p.get('port')
        if not server or not port:
            return None, None
        
        # Exclude loopback
        if server in ('127.0.0.1', 'localhost', '::1'):
            return None, None
            
        success, ip = check_tcp_port(server, port, timeout=1.0)
        if success:
            return p, ip
        return None, None

    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        results = executor.map(worker, proxies)
        
    for p, ip in results:
        if p is not None:
            alive_proxies.append((p, ip))
            
    return alive_proxies

def normalize_ws_path(path):
    """Normalize WebSocket path: URL-decode, collapse slashes, ensure leading slash."""
    if not isinstance(path, str):
        return '/'
    path = urllib.parse.unquote(path).strip()
    if not path.startswith('/'):
        path = '/' + path
    # Collapse consecutive slashes while preserving the leading slash
    path = re.sub(r'/+', '/', path)
    return path if path else '/'


def sanitize_alpn(alpn):
    """Sanitize ALPN value(s): URL-decode, split comma-separated entries, keep only valid protocols."""
    if alpn is None:
        return None
    if isinstance(alpn, str):
        alpn = [alpn]
    if not isinstance(alpn, list):
        return None

    cleaned = []
    for item in alpn:
        if not isinstance(item, str):
            continue
        item = urllib.parse.unquote(item)
        for part in item.split(','):
            part = part.strip()
            if part in VALID_ALPN_PROTOCOLS:
                cleaned.append(part)

    # Remove duplicates while preserving order
    seen = set()
    unique = []
    for val in cleaned:
        if val not in seen:
            seen.add(val)
            unique.append(val)
    return unique if unique else None


def sanitize_proxy_fields(proxies):
    """Apply field-level sanitization to each proxy node."""
    for p in proxies:
        ws_opts = p.get('ws-opts')
        if isinstance(ws_opts, dict) and 'path' in ws_opts:
            ws_opts['path'] = normalize_ws_path(ws_opts['path'])

        if 'alpn' in p:
            sanitized = sanitize_alpn(p['alpn'])
            if sanitized is None:
                p.pop('alpn', None)
            else:
                p['alpn'] = sanitized


def purify_yaml(file_path, db_path):
    print(f"Purifying {file_path}...")
    if not os.path.exists(file_path):
        print(f"Error: {file_path} does not exist.")
        return None, 0, 0
        
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
        
    # Pre-process raw text to fix unquoted IPv6 and remove control characters
    content = re.sub(r'server:\s+([^\s\"\'\{][^,\}\n]*)', r'server: "\1"', content)
    content = re.sub(r'[\x00-\x08\x0b-\x0c\x0e-\x1f\x7f]', '', content)
    
    config = yaml.safe_load(content)
    if not config or 'proxies' not in config:
        print("No proxies found in configuration.")
        return None, 0, 0
        
    proxies = config['proxies']
    total_initial = len(proxies)
    
    # Store initial name map to rename references in proxy-groups later
    name_map = {p['name']: p['name'] for p in proxies}
    
    # Define metric trackers for 10 distinct layers
    # Order: low-cost instant layers first, then dedup, then high-cost protocol layers
    layer1 = FilterMetrics("Server 主机过滤")
    layer2 = FilterMetrics("Port 端口过滤")
    layer3 = FilterMetrics("SS Cipher 过滤")
    layer4 = FilterMetrics("Reality Short-ID 过滤")
    layer5 = FilterMetrics("UUID 格式过滤")
    layer6 = FilterMetrics("Identity 节点去重")
    layer7 = FilterMetrics("TCP 连通性过滤(1s)")
    layer8 = FilterMetrics("TLS 握手验证")
    layer9 = FilterMetrics("Trojan 协议验证")
    layer10 = FilterMetrics("GeoIP 地区标记")
    
    # ------------------ Layer 1: Server ------------------
    layer1.start(len(proxies))
    l1_proxies = []
    for p in proxies:
        server = p.get('server')
        if not server or not isinstance(server, str):
            continue
        if server in ('127.0.0.1', 'localhost', '::1'):
            continue
        l1_proxies.append(p)
    layer1.end(len(l1_proxies))
    
    # ------------------ Layer 2: Port ------------------
    layer2.start(len(l1_proxies))
    l2_proxies = []
    for p in l1_proxies:
        port = p.get('port')
        try:
            port_val = int(port)
            if 0 < port_val <= 65535:
                p['port'] = port_val
                l2_proxies.append(p)
        except (ValueError, TypeError):
            continue
    layer2.end(len(l2_proxies))
    
    # ------------------ Layer 3: SS Cipher ------------------
    layer3.start(len(l2_proxies))
    l3_proxies = []
    for p in l2_proxies:
        cipher = p.get('cipher')
        if cipher == 'ss':
            continue
        if cipher == 'chacha20-poly1305':
            p['cipher'] = 'chacha20-ietf-poly1305'
        l3_proxies.append(p)
    layer3.end(len(l3_proxies))
    
    # ------------------ Layer 4: Reality Short-ID ------------------
    layer4.start(len(l3_proxies))
    l4_proxies = []
    for p in l3_proxies:
        ptype = p.get('type')
        valid = True
        if ptype == 'vless':
            opts = p.get('reality-opts', {})
            sid = opts.get('short-id')
            if sid is not None:
                sid_str = str(sid)
                try:
                    bytes.fromhex(sid_str)
                    if len(sid_str) % 2 != 0 or len(sid_str) > 16:
                        valid = False
                except Exception:
                    valid = False
        if valid:
            l4_proxies.append(p)
    layer4.end(len(l4_proxies))
    
    # ------------------ Layer 5: UUID ------------------
    layer5.start(len(l4_proxies))
    l5_proxies = []
    for p in l4_proxies:
        ptype = p.get('type')
        valid = True
        if ptype in ('vmess', 'vless'):
            uuid_str = p.get('uuid')
            if not uuid_str or not isinstance(uuid_str, str) or len(uuid_str) != 36:
                valid = False
        if valid:
            l5_proxies.append(p)
    layer5.end(len(l5_proxies))
    
    # ------------------ Layer 6: Identity Deduplication ------------------
    layer6.start(len(l5_proxies))
    l6_proxies = []
    seen_keys = set()
    
    for p in l5_proxies:
        ptype = p.get('type')
        server = p.get('server')
        port = p.get('port')
        
        cred = ""
        if ptype in ('vless', 'vmess'):
            cred = p.get('uuid', '')
        elif ptype in ('ss', 'trojan'):
            cred = p.get('password', '')
            
        identity_key = (ptype, server, port, cred)
        
        if identity_key not in seen_keys:
            seen_keys.add(identity_key)
            l6_proxies.append(p)
            
    layer6.end(len(l6_proxies))
    
    # ------------------ Layer 7: TCP Connectivity ------------------
    layer7.start(len(l6_proxies))
    print(f"Performing TCP connectivity checks on {len(l6_proxies)} endpoints...")
    l7_results = check_all_proxies_connectivity(l6_proxies)
    l7_proxies = [item[0] for item in l7_results]
    layer7.end(len(l7_proxies))
    
    # Map from proxy index in l7_proxies to resolved IP
    proxy_ips = {id(item[0]): item[1] for item in l7_results}
    
    # ------------------ Layer 8: TLS Handshake ------------------
    layer8.start(len(l7_proxies))
    print(f"Performing TLS handshake checks on TLS-enabled nodes...")
    tls_proxies = [p for p in l7_proxies if p.get('tls') == True]
    nontls_proxies = [p for p in l7_proxies if p.get('tls') != True]
    
    def tls_worker(p):
        server = p['server']
        port = p['port']
        sni = p.get('sni') or p.get('servername')
        try:
            ctx = ssl.create_default_context()
            ctx.check_hostname = False
            ctx.verify_mode = ssl.CERT_NONE
            with socket.create_connection((server, port), timeout=1.0) as sock:
                with ctx.wrap_socket(sock, server_hostname=sni or server) as ssock:
                    ssock.do_handshake()
            return p
        except Exception:
            return None
    
    l8_proxies = list(nontls_proxies)
    if tls_proxies:
        with concurrent.futures.ThreadPoolExecutor(max_workers=100) as executor:
            for result in executor.map(tls_worker, tls_proxies):
                if result is not None:
                    l8_proxies.append(result)
    layer8.end(len(l8_proxies))
    
    # ------------------ Layer 9: Trojan Protocol ------------------
    layer9.start(len(l8_proxies))
    print(f"Performing Trojan protocol verification...")
    trojan_proxies = [p for p in l8_proxies if p.get('type') == 'trojan' and not p.get('network') == 'ws']
    nontrojan_proxies = [p for p in l8_proxies if not (p.get('type') == 'trojan' and not p.get('network') == 'ws')]
    
    def trojan_worker(p):
        server = p['server']
        port = p['port']
        password = p.get('password', '')
        tls = p.get('tls', False)
        sni = p.get('sni') or p.get('servername')
        try:
            sock = socket.create_connection((server, port), timeout=1.0)
            if tls:
                ctx = ssl.create_default_context()
                ctx.check_hostname = False
                ctx.verify_mode = ssl.CERT_NONE
                sock = ctx.wrap_socket(sock, server_hostname=sni or server)
            sock.settimeout(2.0)
            sock.sendall(f"{password}\r\n".encode())
            try:
                sock.recv(1)
                result = p
            except socket.timeout:
                result = p
            except ConnectionResetError:
                result = None
            finally:
                sock.close()
            return result
        except Exception:
            return None
    
    l9_proxies = list(nontrojan_proxies)
    if trojan_proxies:
        with concurrent.futures.ThreadPoolExecutor(max_workers=100) as executor:
            for result in executor.map(trojan_worker, trojan_proxies):
                if result is not None:
                    l9_proxies.append(result)
    layer9.end(len(l9_proxies))
    
    # ------------------ Layer 10: GeoIP Tagging ------------------
    layer10.start(len(l9_proxies))
    l10_proxies = []
    with GeoIPLookup(db_path) as geoip:
        for p in l9_proxies:
            # Skip if already tagged with [XX] prefix
            if re.match(r'^\[\w{2}\] ', p['name']):
                l10_proxies.append(p)
                continue
            
            ip = proxy_ips.get(id(p))
            country = geoip.lookup(ip)
            
            # Rename the proxy to prefix country code
            old_name = p['name']
            new_name = f"[{country}] {old_name}"
            p['name'] = new_name
            name_map[old_name] = new_name
            
            l10_proxies.append(p)
    layer10.end(len(l10_proxies))
    
    # Save the cleaned proxies
    config['proxies'] = l10_proxies

    # Sanitize protocol-specific fields (URL-encoded paths, invalid ALPN values, etc.)
    sanitize_proxy_fields(l10_proxies)

    valid_names_new = {p['name'] for p in l10_proxies}
    
    # Collect unique country codes from purified proxies with node counts
    code_count = {}
    for p in l10_proxies:
        if p['name'].startswith('[') and ']' in p['name']:
            c = p['name'].split(']')[0].lstrip('[')
            code_count[c] = code_count.get(c, 0) + 1
    
    discovered_codes = sorted(code_count.keys())
    countries_data = [
        {"code": c, "name": COUNTRY_NAMES.get(c, c), "emoji": iso_code_to_flag(c), "count": code_count[c]}
        for c in discovered_codes
    ]
    # Write countries list for publish.sh (only from proxy-provider pool)
    if 'proxies.yaml' in file_path:
        countries_json_path = 'docs/.countries.json'
        with open(countries_json_path, 'w', encoding='utf-8') as f:
            json.dump(countries_data, f, ensure_ascii=False)
        print(f"Discovered {len(countries_data)} regions: {[c['code'] for c in countries_data]}")
    
    # Define mapping from standard regional group names to country code prefix
    regional_groups_map = {
        '🇭🇰 香港节点': 'HK',
        '🇹🇼 台湾节点': 'TW',
        '🇯🇵 日本节点': 'JP',
        '🇸🇬 狮城节点': 'SG',
        '🇺🇸 美国节点': 'US'
    }
    
    # Update proxy names, regroup regional groups, and remove dropped ones
    if 'proxy-groups' in config:
        for group in config['proxy-groups']:
            gname = group.get('name')
            if gname in regional_groups_map:
                # Regroup regional groups using GeoIP tags from purified proxies
                target_code = regional_groups_map[gname]
                group['proxies'] = [p['name'] for p in l10_proxies if p['name'].startswith(f"[{target_code}]")]
            elif 'proxies' in group and isinstance(group['proxies'], list):
                # For non-regional groups, update names and remove dropped ones
                new_group_proxies = []
                for name in group['proxies']:
                    if name in name_map:
                        new_name = name_map[name]
                        if new_name in valid_names_new:
                            new_group_proxies.append(new_name)
                    else:
                        new_group_proxies.append(name)
                group['proxies'] = new_group_proxies
        
        # Add dynamic proxy groups for countries not in the hardcoded map
        existing_codes = set(regional_groups_map.values())
        countries_with_groups = set()
        for g in config['proxy-groups']:
            if 'proxies' in g and isinstance(g['proxies'], list):
                for pname in g['proxies']:
                    m = re.match(r'^\[(\w{2})\]', pname)
                    if m:
                        countries_with_groups.add(m.group(1))
        
        # Separate into large (≥MIN_NODES_FOR_GROUP) and small (< threshold + UN)
        large_countries = [
            c for c in countries_data
            if c["code"] not in existing_codes
            and c["code"] not in countries_with_groups
            and c["code"] != "UN"
            and c["count"] >= MIN_NODES_FOR_GROUP
        ]
        small_codes = [
            c for c in countries_data
            if c["code"] not in existing_codes
            and c["code"] not in countries_with_groups
            and (c["count"] < MIN_NODES_FOR_GROUP or c["code"] == "UN")
        ]
        
        # Create dedicated groups for large countries
        for nc in large_countries:
            group_name = f"{nc['emoji']} {nc['name']}节点"
            new_group = {
                "name": group_name,
                "type": "url-test",
                "proxies": [p['name'] for p in l10_proxies if p['name'].startswith(f"[{nc['code']}]")],
                "url": "https://cp.cloudflare.com/generate_204",
                "interval": 300,
                "tolerance": 50,
            }
            insert_idx = -1
            for i, g in enumerate(config['proxy-groups']):
                if g.get('name') == '♻️ 自动选择':
                    insert_idx = i
                    break
            if insert_idx >= 0:
                config['proxy-groups'].insert(insert_idx, new_group)
            else:
                config['proxy-groups'].append(new_group)
            
            for g in config['proxy-groups']:
                if g.get('name') == '🚀 节点选择' and 'proxies' in g and isinstance(g['proxies'], list):
                    g['proxies'].insert(-1, group_name)
                    break
            for g in config['proxy-groups']:
                if g.get('name') == '🔯 故障转移' and 'proxies' in g and isinstance(g['proxies'], list):
                    g['proxies'].append(group_name)
                    break
        
        # Create 🌍 其他地区 group for small countries
        other_proxies = []
        for c in small_codes:
            other_proxies.extend(
                p['name'] for p in l10_proxies if p['name'].startswith(f"[{c['code']}]")
            )
        if other_proxies:
            other_group = {
                "name": "🌍 其他地区",
                "type": "url-test",
                "proxies": other_proxies,
                "url": "https://cp.cloudflare.com/generate_204",
                "interval": 300,
                "tolerance": 50,
            }
            insert_idx = -1
            for i, g in enumerate(config['proxy-groups']):
                if g.get('name') == '♻️ 自动选择':
                    insert_idx = i
                    break
            if insert_idx >= 0:
                config['proxy-groups'].insert(insert_idx, other_group)
            else:
                config['proxy-groups'].append(other_group)
            
            for g in config['proxy-groups']:
                if g.get('name') == '🚀 节点选择' and 'proxies' in g and isinstance(g['proxies'], list):
                    g['proxies'].insert(-1, "🌍 其他地区")
                    break
            for g in config['proxy-groups']:
                if g.get('name') == '🔯 故障转移' and 'proxies' in g and isinstance(g['proxies'], list):
                    g['proxies'].append("🌍 其他地区")
                    break
                
    output_content = yaml.safe_dump(config, allow_unicode=True, default_flow_style=False, sort_keys=False)
    output_content = re.sub(r'server:\s+([^\s\"\'\{][^,\}\n]*)', r'server: "\1"', output_content)
    output_content = re.sub(r'[\x00-\x08\x0b-\x0c\x0e-\x1f\x7f]', '', output_content)
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(output_content)
        
    print(f"Purification completed. Remaining proxies: {len(l10_proxies)} / {total_initial}")
    return [layer1, layer2, layer3, layer4, layer5, layer6, layer7, layer8, layer9, layer10], total_initial, len(l10_proxies)

def generate_report(metrics_list, initial, final):
    report_path = 'docs/filter_report.md'
    total_duration = sum(m.duration_ms for m in metrics_list)
    total_filtered = initial - final
    total_rate = (total_filtered / initial * 100.0) if initial > 0 else 0.0
    
    rows = []
    for i, m in enumerate(metrics_list):
        rows.append(
            f"| {i+1}. {m.name} | {m.input_count} | {m.output_count} | {m.filtered_count} | {m.filter_rate_pct:.2f}% | {m.duration_ms:.4f} ms |"
        )
    table_content = "\n".join(rows)
    
    report_content = f"""# 节点过滤与评估报告 (Node Filtering Evaluation Report)

*生成时间 (UTC): {time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime())}*

### 📊 过滤层级度量数据 (Metrics by Filtering Layer)

| 过滤层级 (Filter Layer) | 输入节点数 | 留存节点数 | 过滤节点数 | 过滤占比 | 耗时 (ms) |
| :--- | :---: | :---: | :---: | :---: | :---: |
{table_content}

### 📈 过滤效果综合评价 (Overall Evaluation)

- **原始节点总数 (Initial Nodes)**: `{initial}`
- **净化后有效节点数 (Retained Nodes)**: `{final}`
- **过滤及去重节点总数 (Filtered Total)**: `{total_filtered}`
- **整体过滤/去重率 (Overall Filtering Rate)**: `{total_rate:.2f}%`
- **总处理耗时 (Total Duration)**: `{total_duration:.4f} ms`

---
*注：本报告由自动化节点净化脚本自动生成。*
"""
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report_content)
    print(f"Report generated at {report_path}")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python purify.py <path_to_yaml> [path_to_mmdb]")
        sys.exit(1)
        
    target_file = sys.argv[1]
    db_file = sys.argv[2] if len(sys.argv) > 2 else 'config/GeoLite2-Country.mmdb'
    metrics, initial, final = purify_yaml(target_file, db_file)
    
    if metrics and 'proxies.yaml' in target_file:
        generate_report(metrics, initial, final)
